groups:
- name: VMNetwork
  rules:
  - alert: VMUnusualNetworkThroughputIn
    expr: irate(libvirt_domain_interface_stats_receive_bytes_total[5m]) * on(domain,instance) group_left(uuid,instance_name) (libvirt_domain_info_meta) / 1024 / 1024  > 1024
    for: 1m
    labels:
      severity: warning
    annotations:
            description: "Unusual network throughput In (>1GB): \n - uuid: {{ $labels.uuid }}\n - Instance_Name: {{ $labels.instance_name }}\n - VALUE = {{ $value }} (MB/s)\n - INTERFACE: {{ $labels.target_device }}\n - IP_Compute: {{ $labels.instance }}\n\n"

  - alert: VMUnusualNetworkThroughputIn
    expr: irate(libvirt_domain_interface_stats_receive_bytes_total[5m]) * on(domain,instance) group_left(uuid,instance_name) (libvirt_domain_info_meta) / 1024 / 1024 > 1536
    for: 1m
    labels:
      severity: critical
    annotations:
            description: "Unusual network throughput In (>1.5GB): \n - uuid: {{ $labels.uuid }}\n - Instance_Name: {{ $labels.instance_name }}\n - VALUE = {{ $value }} (MB/s)\n - INTERFACE: {{ $labels.target_device }}\n - IP_Compute: {{ $labels.instance }}\n\n"
  - alert: VMUnusualNetworkThroughputOut
    expr: irate(libvirt_domain_interface_stats_transmit_bytes_total[5m])* on(domain,instance) group_left(uuid,instance_name) (libvirt_domain_info_meta) / 1024 / 1024 > 1024
    for: 1m
    labels:
      severity: warning
    annotations:
            description: "Unusual network throughput Out (>1GB): \n - VM_UUID: {{ $labels.uuid }}\n - Instance_Name: {{ $labels.instance_name }}\n - VALUE = {{ $value }} (MB/s)\n - INTERFACE: {{ $labels.target_device }}\n - IP_Compute: {{ $labels.instance }}\n\n"
  - alert: VMUnusualNetworkThroughputOut
    expr: irate(libvirt_domain_interface_stats_transmit_bytes_total[5m])* on(domain,instance) group_left(uuid,instance_name) (libvirt_domain_info_meta) / 1024 / 1024 > 1536
    for: 1m
    labels:
      severity: critical
    annotations:
            description: "Unusual network throughput Out (>1.5GB): \n - VM_UUID: {{ $labels.uuid }}\n - Instance_Name: {{ $labels.instance_name }}\n - VALUE = {{ $value }} (MB/s)\n - INTERFACE: {{ $labels.target_device }}\n - IP_Compute: {{ $labels.instance }}\n\n"